### ISSUE TITLE
Not compatible with Swift 4.2

### ISSUE THREAD

**Issue by tonyxu-io** [sauvikdolui/SDStateTableView#7]
Lot's of incompatible implementations with Swift 4.2, needs update.

**Comment by sauvikdolui** [comment]
Hi @tonyxu-io Tonight have published a new version, can you please try it? I have also found that the last version was compatible with `Swift 4.2`. I was able to run it successfully. It will be helpful for me to debug if you provide me details of the issues you are facing.

![screenshot 2018-12-30 at 2 05 55 am](https://user-images.githubusercontent.com/14096115/50541997-e0dd8980-0bd7-11e9-8122-76fd2e0315ea.png)

**Comment by tonyxu-io** [comment]
Hi, it works now. Thanks for the quick update! Appreciate and happy new year.
